from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .models import CodePatch


def _clean(text: object, *, limit: int = 200) -> str:
    """Flatten model-provided text to a safe single line for git/PR metadata.

    Strips backticks, newlines and control chars (which could break Markdown
    tables or smuggle formatting) and caps the length.
    """
    flattened = re.sub(r"[`\r\n\t]+", " ", str(text or ""))
    flattened = re.sub(r"\s+", " ", flattened).strip()
    return flattened[:limit]


@dataclass(frozen=True)
class PrResult:
    url: str
    branch: str


class GitPrManager:
    """Git branch/commit/push and optional GitHub PR creation via `gh`."""

    def __init__(self, project_root: Path, *, remote: str = "origin", base_branch: str = "main") -> None:
        self.project_root = project_root
        self.remote = remote
        self.base_branch = base_branch

    def commit_only(self, patches: list[CodePatch]) -> str:
        branch = self._create_branch(patches)
        self._stage(patches)
        self._run(["git", "commit", "-m", self._commit_message(patches)])
        return branch

    def commit_and_pr(self, patches: list[CodePatch]) -> PrResult:
        branch = self.commit_only(patches)
        self._run(["git", "push", self.remote, branch, "--set-upstream"])
        url = self._create_pr(branch, patches)
        return PrResult(url=url, branch=branch)

    def _create_branch(self, patches: list[CodePatch]) -> str:
        stem = Path(patches[0].file_path).stem if patches else "fix"
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        branch = f"self-heal/{stem}-{timestamp}"
        self._run(["git", "checkout", "-b", branch])
        return branch

    def _stage(self, patches: list[CodePatch]) -> None:
        for file_path in {patch.file_path for patch in patches}:
            self._run(["git", "add", file_path])

    def _commit_message(self, patches: list[CodePatch]) -> str:
        files = sorted({Path(patch.file_path).name for patch in patches})
        lines = [f"fix: auto-heal broken locator(s) in {', '.join(files)}", ""]
        for patch in patches:
            lines.append(f"- {patch.file_path}:{patch.line_number}")
            lines.append(f"  old: {_clean(patch.suggestion.old_locator)}")
            lines.append(f"  new: {_clean(patch.suggestion.new_locator)}")
            lines.append(f"  confidence: {patch.suggestion.confidence:.0%}")
        lines.append("")
        lines.append("Generated by ai-auto-healer")
        return "\n".join(lines)

    def _create_pr(self, branch: str, patches: list[CodePatch]) -> str:
        title = "Self-heal: fix broken locator(s)"
        body = self._pr_body(patches)
        result = self._run(
            [
                "gh",
                "pr",
                "create",
                "--title",
                title,
                "--body",
                body,
                "--base",
                self.base_branch,
                "--head",
                branch,
            ]
        )
        return result.stdout.strip()

    def _pr_body(self, patches: list[CodePatch]) -> str:
        lines = ["## Self-Healing Test Fix", "", "Automatically generated by ai-auto-healer.", ""]
        for patch in patches:
            lines.append(f"### `{patch.file_path}` (line {patch.line_number})")
            lines.append("")
            lines.append("| | Locator |")
            lines.append("|---|---|")
            lines.append(f"| Before | `{_clean(patch.suggestion.old_locator)}` |")
            lines.append(f"| After | `{_clean(patch.suggestion.new_locator)}` |")
            lines.append(f"| Confidence | {patch.suggestion.confidence:.0%} |")
            lines.append("")
            lines.append(f"Reasoning: {_clean(patch.suggestion.reasoning, limit=500)}")
            lines.append("")
        lines.append("> Please review the locator changes before merging.")
        return "\n".join(lines)

    def _run(self, args: list[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            args,
            cwd=self.project_root,
            check=True,
            capture_output=True,
            text=True,
            timeout=120,
        )
