import simpleGit, { SimpleGit } from 'simple-git';
import { execSync } from 'child_process';
import { CodePatch, GitConfig } from '../types';

export interface PrResult {
  url: string;
  number: number;
  branch: string;
}

/**
 * Handles git operations: branch, commit, push, and PR creation.
 */
export class GitPrManager {
  private git: SimpleGit;

  constructor(
    private projectRoot: string,
    private config: GitConfig
  ) {
    this.git = simpleGit(projectRoot);
  }

  /**
   * Create a branch, commit the patch, push, and create a PR.
   */
  async commitAndPr(patches: CodePatch[]): Promise<PrResult> {
    const branchName = this.generateBranchName(patches);

    // Create and checkout a new branch
    await this.git.checkoutLocalBranch(branchName);

    // Stage patched files
    const filePaths = [...new Set(patches.map(p => p.filePath))];
    for (const filePath of filePaths) {
      await this.git.add(filePath);
    }

    // Commit
    const commitMessage = this.buildCommitMessage(patches);
    await this.git.commit(commitMessage);

    // Push
    const remote = this.config.remote || 'origin';
    await this.git.push(remote, branchName, ['--set-upstream']);

    // Create PR using gh CLI
    const prResult = this.createPullRequest(branchName, patches);

    return prResult;
  }

  /**
   * Commit changes without creating a PR.
   */
  async commitOnly(patches: CodePatch[]): Promise<string> {
    const branchName = this.generateBranchName(patches);
    await this.git.checkoutLocalBranch(branchName);

    const filePaths = [...new Set(patches.map(p => p.filePath))];
    for (const filePath of filePaths) {
      await this.git.add(filePath);
    }

    const commitMessage = this.buildCommitMessage(patches);
    const result = await this.git.commit(commitMessage);
    return result.commit;
  }

  private generateBranchName(patches: CodePatch[]): string {
    const prefix = this.config.branchPrefix || 'self-heal';
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const testFile = patches[0]?.filePath
      .split(/[/\\]/)
      .pop()
      ?.replace(/\.(spec|test)\.(ts|js|mjs)$/, '') || 'fix';
    return `${prefix}/${testFile}-${timestamp}`;
  }

  private buildCommitMessage(patches: CodePatch[]): string {
    if (this.config.commitMessage) {
      return this.config.commitMessage;
    }

    const files = [...new Set(patches.map(p => {
      const parts = p.filePath.split(/[/\\]/);
      return parts[parts.length - 1];
    }))];

    let message = `fix: auto-heal broken locator(s) in ${files.join(', ')}\n\n`;
    message += 'Self-healing applied the following patches:\n\n';

    for (const patch of patches) {
      message += `- ${patch.filePath}:${patch.lineNumber}\n`;
      message += `  Old: ${patch.locatorFix.oldLocator}\n`;
      message += `  New: ${patch.locatorFix.newLocator}\n`;
      message += `  Strategy: ${patch.locatorFix.strategy}\n`;
      message += `  Confidence: ${(patch.locatorFix.confidence * 100).toFixed(0)}%\n\n`;
    }

    message += 'Generated by playwright-self-heal';
    return message;
  }

  private createPullRequest(branchName: string, patches: CodePatch[]): PrResult {
    const title = this.config.prTitle ||
      `🩹 Self-heal: fix broken locator(s)`;

    const body = this.config.prBody || this.buildPrBody(patches);
    const baseBranch = this.config.baseBranch || 'main';

    try {
      const output = execSync(
        `gh pr create --title "${this.escapeShell(title)}" ` +
        `--body "${this.escapeShell(body)}" ` +
        `--base "${baseBranch}" ` +
        `--head "${branchName}"`,
        {
          cwd: this.projectRoot,
          encoding: 'utf-8',
          stdio: ['pipe', 'pipe', 'pipe'],
        }
      );

      const prUrl = output.trim();
      const prNumberMatch = prUrl.match(/\/pull\/(\d+)/);

      return {
        url: prUrl,
        number: prNumberMatch ? parseInt(prNumberMatch[1], 10) : 0,
        branch: branchName,
      };
    } catch (error: unknown) {
      const execError = error as { stderr?: string };
      throw new Error(`Failed to create PR: ${execError.stderr || String(error)}`);
    }
  }

  private buildPrBody(patches: CodePatch[]): string {
    let body = '## 🩹 Self-Healing Test Fix\n\n';
    body += 'This PR was automatically generated by `playwright-self-heal`.\n\n';
    body += '### Changes\n\n';

    for (const patch of patches) {
      body += `#### \`${patch.filePath}\` (line ${patch.lineNumber})\n\n`;
      body += '| | Locator |\n|---|---|\n';
      body += `| **Before** | \`${patch.locatorFix.oldLocator}\` |\n`;
      body += `| **After** | \`${patch.locatorFix.newLocator}\` |\n`;
      body += `| **Strategy** | ${patch.locatorFix.strategy} |\n`;
      body += `| **Confidence** | ${(patch.locatorFix.confidence * 100).toFixed(0)}% |\n\n`;
      body += `**Reasoning:** ${patch.locatorFix.reasoning}\n\n`;
    }

    body += '---\n';
    body += '> ⚠️ Please review the locator changes before merging.\n';
    return body;
  }

  private escapeShell(str: string): string {
    return str.replace(/"/g, '\\"');
  }
}
